name: Tests

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Project
        run: |
          git config --global url."https://${{ secrets.GH_PROJECT_PAT }}@github.com".insteadOf https://github.com
          rustup default nightly
          cargo install cargo2junit

      - name: Cargo Test
        run: |
          cd endpoint
          cargo test -- -Z unstable-options --format json --report-time | cargo2junit > test-results.xml

      - name: Upload Results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: endpoint/test-results.xml
